// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePlayset(arg1, arg2) {
  return window['go']['main']['App']['DeletePlayset'](arg1, arg2);
}

export function DetectGames() {
  return window['go']['main']['App']['DetectGames']();
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListPlaysets(arg1) {
  return window['go']['main']['App']['ListPlaysets'](arg1);
}

export function LoadPlayset(arg1, arg2) {
  return window['go']['main']['App']['LoadPlayset'](arg1, arg2);
}

export function SavePlayset(arg1) {
  return window['go']['main']['App']['SavePlayset'](arg1);
}

export function ScanGame(arg1, arg2) {
  return window['go']['main']['App']['ScanGame'](arg1, arg2);
}
