// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {about} from '../models';
import {library} from '../models';
import {main} from '../models';
import {modupdates} from '../models';
import {dlcstore} from '../models';
import {gamelog} from '../models';
import {gameproc} from '../models';
import {preferences} from '../models';
import {launcherdb} from '../models';
import {backup} from '../models';
import {collection} from '../models';
import {dlc} from '../models';
import {playset} from '../models';
import {applog} from '../models';
import {steamapi} from '../models';

export function AboutInfo():Promise<about.Info>;

export function AuthorProfiles(arg1:string):Promise<Array<library.AuthorProfile>>;

export function BackgroundCatalog(arg1:boolean):Promise<main.BackgroundCatalog>;

export function BackgroundImages(arg1:string):Promise<Array<string>>;

export function BackupMod(arg1:string,arg2:string):Promise<string>;

export function BackupOverview(arg1:string):Promise<main.BackupOverview>;

export function BackupStatus():Promise<main.BackupStatus>;

export function BrowseForAnyGameInstall():Promise<library.DetectedGame>;

export function BrowseForBackupFolder():Promise<main.BackupStatus>;

export function BrowseForExtraModFolder(arg1:string):Promise<string>;

export function BrowseForGameInstall(arg1:string):Promise<library.DetectedGame>;

export function CancelBackgroundDownload():Promise<void>;

export function CheckGameUpdates():Promise<Array<library.GameUpdate>>;

export function CheckModUpdates(arg1:string,arg2:boolean):Promise<modupdates.Report>;

export function CheckSteamAPIKey():Promise<main.SteamAPIStatus>;

export function ClearGamePath(arg1:string):Promise<library.DetectedGame>;

export function ClearLog():Promise<void>;

export function ClearPatchOverrides(arg1:string):Promise<void>;

export function DLCStoreData(arg1:string):Promise<Array<dlcstore.StoreData>>;

export function DeleteBackups(arg1:string,arg2:string,arg3:Array<string>):Promise<main.BackupDeleteResult>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeletePlayset(arg1:string,arg2:string):Promise<void>;

export function DetectGames():Promise<Array<library.DetectedGame>>;

export function DeveloperToolsStatus():Promise<main.DeveloperToolsStatus>;

export function FindEmptyMods(arg1:string):Promise<Array<library.EmptyModCandidate>>;

export function GameLogFiles(arg1:string):Promise<gamelog.Listing>;

export function GameMedia(arg1:string,arg2:string):Promise<string>;

export function GameStatus(arg1:string):Promise<gameproc.Status>;

export function GameVersion(arg1:string):Promise<string>;

export function GeneratePatch(arg1:string,arg2:Array<string>):Promise<library.PatchResult>;

export function GetPreferences():Promise<preferences.Preferences>;

export function IgnoredIncompatibleMods(arg1:string):Promise<Array<string>>;

export function ImportLauncherPlaysets(arg1:string):Promise<Array<launcherdb.Playset>>;

export function LaunchGame(arg1:string,arg2:string):Promise<void>;

export function LicenceText():Promise<string>;

export function ListBackups(arg1:string):Promise<Array<backup.Entry>>;

export function ListCollections():Promise<Array<collection.Collection>>;

export function ListDLC(arg1:string):Promise<Array<dlc.Entry>>;

export function ListGames():Promise<Array<library.GameInfo>>;

export function ListModFiles(arg1:string,arg2:string):Promise<library.ModFiles>;

export function ListPlaysets(arg1:string):Promise<Array<string>>;

export function LoadPlayset(arg1:string,arg2:string):Promise<playset.Playset>;

export function LogEntries():Promise<Array<applog.Entry>>;

export function LogEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MarkModUpdatesSeen(arg1:string):Promise<modupdates.Report>;

export function ModChangelog(arg1:string):Promise<Array<steamapi.ChangelogEntry>>;

export function ModNotes(arg1:string):Promise<Record<string, string>>;

export function ModSizes(arg1:string):Promise<Record<string, number>>;

export function ModThumbnail(arg1:string,arg2:string):Promise<string>;

export function OpenBackupFolder(arg1:string):Promise<void>;

export function OpenModFolder(arg1:string,arg2:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PlanBackupCleanup(arg1:string,arg2:string):Promise<main.BackupCleanupPlan>;

export function PlaysetChecksum(arg1:string,arg2:string):Promise<main.PlaysetChecksumResult>;

export function PurgeMods(arg1:string,arg2:Array<string>):Promise<library.PurgeResult>;

export function ReadModFile(arg1:string,arg2:string,arg3:string):Promise<library.ModFileContent>;

export function RemoveBackgroundPack(arg1:string):Promise<void>;

export function RemoveExtraModFolder(arg1:string,arg2:string):Promise<void>;

export function RenamePlayset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResolvedConflicts(arg1:string):Promise<Array<string>>;

export function SaveCollection(arg1:collection.Collection):Promise<void>;

export function SavePlayset(arg1:playset.Playset):Promise<void>;

export function SaveSteamAPIKey(arg1:string,arg2:string):Promise<main.SteamAPIStatus>;

export function ScanGame(arg1:string,arg2:string):Promise<library.Summary>;

export function SetBackupFolder(arg1:string):Promise<main.BackupStatus>;

export function SetBackupLimits(arg1:boolean,arg2:number,arg3:boolean,arg4:number):Promise<main.BackupStatus>;

export function SetBackupMode(arg1:string):Promise<main.BackupStatus>;

export function SetConflictResolved(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetGameManaged(arg1:string,arg2:boolean):Promise<void>;

export function SetModIncompatibilityIgnored(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetModNote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetPatchOverride(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetPreferences(arg1:preferences.Preferences):Promise<void>;

export function SetStaticBackground(arg1:string,arg2:string):Promise<void>;

export function SetSteamAPIMode(arg1:string):Promise<main.SteamAPIStatus>;

export function StartBackgroundDownload(arg1:Array<string>):Promise<void>;

export function StartupNotice():Promise<string>;

export function SteamAPIStatus():Promise<main.SteamAPIStatus>;

export function StopGame(arg1:string):Promise<number>;

export function StopWatchingGameLog():Promise<void>;

export function WatchGameLog(arg1:string,arg2:string):Promise<number>;

export function WatchMods(arg1:string):Promise<void>;

export function WorkshopAvailability(arg1:string):Promise<Array<main.WorkshopAvailability>>;

export function WorkshopDetails(arg1:string):Promise<Array<steamapi.PublishedFileDetails>>;
