// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';
import {playset} from '../models';

export function DeletePlayset(arg1:string,arg2:string):Promise<void>;

export function DetectGames():Promise<Array<library.DetectedGame>>;

export function LaunchGame(arg1:string,arg2:string):Promise<void>;

export function ListGames():Promise<Array<library.GameInfo>>;

export function ListPlaysets(arg1:string):Promise<Array<string>>;

export function LoadPlayset(arg1:string,arg2:string):Promise<playset.Playset>;

export function SavePlayset(arg1:playset.Playset):Promise<void>;

export function ScanGame(arg1:string,arg2:string):Promise<library.Summary>;
