// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AboutInfo() {
  return window['go']['main']['App']['AboutInfo']();
}

export function AuthorProfiles(arg1) {
  return window['go']['main']['App']['AuthorProfiles'](arg1);
}

export function BackgroundCatalog(arg1) {
  return window['go']['main']['App']['BackgroundCatalog'](arg1);
}

export function BackgroundImages(arg1) {
  return window['go']['main']['App']['BackgroundImages'](arg1);
}

export function BackupMod(arg1, arg2) {
  return window['go']['main']['App']['BackupMod'](arg1, arg2);
}

export function BackupOverview(arg1) {
  return window['go']['main']['App']['BackupOverview'](arg1);
}

export function BackupStatus() {
  return window['go']['main']['App']['BackupStatus']();
}

export function BrowseForAnyGameInstall() {
  return window['go']['main']['App']['BrowseForAnyGameInstall']();
}

export function BrowseForBackupFolder() {
  return window['go']['main']['App']['BrowseForBackupFolder']();
}

export function BrowseForExtraModFolder(arg1) {
  return window['go']['main']['App']['BrowseForExtraModFolder'](arg1);
}

export function BrowseForGameInstall(arg1) {
  return window['go']['main']['App']['BrowseForGameInstall'](arg1);
}

export function CancelBackgroundDownload() {
  return window['go']['main']['App']['CancelBackgroundDownload']();
}

export function CheckGameUpdates() {
  return window['go']['main']['App']['CheckGameUpdates']();
}

export function CheckModUpdates(arg1, arg2) {
  return window['go']['main']['App']['CheckModUpdates'](arg1, arg2);
}

export function CheckSteamAPIKey() {
  return window['go']['main']['App']['CheckSteamAPIKey']();
}

export function ClearGamePath(arg1) {
  return window['go']['main']['App']['ClearGamePath'](arg1);
}

export function ClearLog() {
  return window['go']['main']['App']['ClearLog']();
}

export function ClearPatchOverrides(arg1) {
  return window['go']['main']['App']['ClearPatchOverrides'](arg1);
}

export function DLCStoreData(arg1) {
  return window['go']['main']['App']['DLCStoreData'](arg1);
}

export function DeleteBackups(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBackups'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeletePlayset(arg1, arg2) {
  return window['go']['main']['App']['DeletePlayset'](arg1, arg2);
}

export function DetectGames() {
  return window['go']['main']['App']['DetectGames']();
}

export function DeveloperToolsStatus() {
  return window['go']['main']['App']['DeveloperToolsStatus']();
}

export function FindEmptyMods(arg1) {
  return window['go']['main']['App']['FindEmptyMods'](arg1);
}

export function GameLogFiles(arg1) {
  return window['go']['main']['App']['GameLogFiles'](arg1);
}

export function GameMedia(arg1, arg2) {
  return window['go']['main']['App']['GameMedia'](arg1, arg2);
}

export function GameStatus(arg1) {
  return window['go']['main']['App']['GameStatus'](arg1);
}

export function GameVersion(arg1) {
  return window['go']['main']['App']['GameVersion'](arg1);
}

export function GeneratePatch(arg1, arg2) {
  return window['go']['main']['App']['GeneratePatch'](arg1, arg2);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function IgnoredIncompatibleMods(arg1) {
  return window['go']['main']['App']['IgnoredIncompatibleMods'](arg1);
}

export function ImportLauncherPlaysets(arg1) {
  return window['go']['main']['App']['ImportLauncherPlaysets'](arg1);
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function LicenceText() {
  return window['go']['main']['App']['LicenceText']();
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListDLC(arg1) {
  return window['go']['main']['App']['ListDLC'](arg1);
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListModFiles(arg1, arg2) {
  return window['go']['main']['App']['ListModFiles'](arg1, arg2);
}

export function ListPlaysets(arg1) {
  return window['go']['main']['App']['ListPlaysets'](arg1);
}

export function LoadPlayset(arg1, arg2) {
  return window['go']['main']['App']['LoadPlayset'](arg1, arg2);
}

export function LogEntries() {
  return window['go']['main']['App']['LogEntries']();
}

export function LogEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogEvent'](arg1, arg2, arg3);
}

export function MarkModUpdatesSeen(arg1) {
  return window['go']['main']['App']['MarkModUpdatesSeen'](arg1);
}

export function ModChangelog(arg1) {
  return window['go']['main']['App']['ModChangelog'](arg1);
}

export function ModSizes(arg1) {
  return window['go']['main']['App']['ModSizes'](arg1);
}

export function ModThumbnail(arg1, arg2) {
  return window['go']['main']['App']['ModThumbnail'](arg1, arg2);
}

export function OpenBackupFolder(arg1) {
  return window['go']['main']['App']['OpenBackupFolder'](arg1);
}

export function OpenModFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenModFolder'](arg1, arg2);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PlanBackupCleanup(arg1, arg2) {
  return window['go']['main']['App']['PlanBackupCleanup'](arg1, arg2);
}

export function PlaysetChecksum(arg1, arg2) {
  return window['go']['main']['App']['PlaysetChecksum'](arg1, arg2);
}

export function PurgeMods(arg1, arg2) {
  return window['go']['main']['App']['PurgeMods'](arg1, arg2);
}

export function ReadModFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadModFile'](arg1, arg2, arg3);
}

export function RemoveBackgroundPack(arg1) {
  return window['go']['main']['App']['RemoveBackgroundPack'](arg1);
}

export function RemoveExtraModFolder(arg1, arg2) {
  return window['go']['main']['App']['RemoveExtraModFolder'](arg1, arg2);
}

export function RenamePlayset(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePlayset'](arg1, arg2, arg3);
}

export function ResolvedConflicts(arg1) {
  return window['go']['main']['App']['ResolvedConflicts'](arg1);
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SavePlayset(arg1) {
  return window['go']['main']['App']['SavePlayset'](arg1);
}

export function SaveSteamAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SaveSteamAPIKey'](arg1, arg2);
}

export function ScanGame(arg1, arg2) {
  return window['go']['main']['App']['ScanGame'](arg1, arg2);
}

export function SetBackupFolder(arg1) {
  return window['go']['main']['App']['SetBackupFolder'](arg1);
}

export function SetBackupLimits(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetBackupLimits'](arg1, arg2, arg3, arg4);
}

export function SetBackupMode(arg1) {
  return window['go']['main']['App']['SetBackupMode'](arg1);
}

export function SetConflictResolved(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetConflictResolved'](arg1, arg2, arg3, arg4);
}

export function SetGameManaged(arg1, arg2) {
  return window['go']['main']['App']['SetGameManaged'](arg1, arg2);
}

export function SetModIncompatibilityIgnored(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModIncompatibilityIgnored'](arg1, arg2, arg3);
}

export function SetPatchOverride(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPatchOverride'](arg1, arg2, arg3, arg4);
}

export function SetPreferences(arg1) {
  return window['go']['main']['App']['SetPreferences'](arg1);
}

export function SetStaticBackground(arg1, arg2) {
  return window['go']['main']['App']['SetStaticBackground'](arg1, arg2);
}

export function SetSteamAPIMode(arg1) {
  return window['go']['main']['App']['SetSteamAPIMode'](arg1);
}

export function StartBackgroundDownload(arg1) {
  return window['go']['main']['App']['StartBackgroundDownload'](arg1);
}

export function StartupNotice() {
  return window['go']['main']['App']['StartupNotice']();
}

export function SteamAPIStatus() {
  return window['go']['main']['App']['SteamAPIStatus']();
}

export function StopGame(arg1) {
  return window['go']['main']['App']['StopGame'](arg1);
}

export function StopWatchingGameLog() {
  return window['go']['main']['App']['StopWatchingGameLog']();
}

export function WatchGameLog(arg1, arg2) {
  return window['go']['main']['App']['WatchGameLog'](arg1, arg2);
}

export function WatchMods(arg1) {
  return window['go']['main']['App']['WatchMods'](arg1);
}

export function WorkshopAvailability(arg1) {
  return window['go']['main']['App']['WorkshopAvailability'](arg1);
}

export function WorkshopDetails(arg1) {
  return window['go']['main']['App']['WorkshopDetails'](arg1);
}
