// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForAnyGameInstall() {
  return window['go']['main']['App']['BrowseForAnyGameInstall']();
}

export function BrowseForGameInstall(arg1) {
  return window['go']['main']['App']['BrowseForGameInstall'](arg1);
}

export function DeletePlayset(arg1, arg2) {
  return window['go']['main']['App']['DeletePlayset'](arg1, arg2);
}

export function DetectGames() {
  return window['go']['main']['App']['DetectGames']();
}

export function GameMedia(arg1, arg2) {
  return window['go']['main']['App']['GameMedia'](arg1, arg2);
}

export function GeneratePatch(arg1, arg2) {
  return window['go']['main']['App']['GeneratePatch'](arg1, arg2);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListModFiles(arg1, arg2) {
  return window['go']['main']['App']['ListModFiles'](arg1, arg2);
}

export function ListPlaysets(arg1) {
  return window['go']['main']['App']['ListPlaysets'](arg1);
}

export function LoadPlayset(arg1, arg2) {
  return window['go']['main']['App']['LoadPlayset'](arg1, arg2);
}

export function ModSizes(arg1) {
  return window['go']['main']['App']['ModSizes'](arg1);
}

export function ModThumbnail(arg1, arg2) {
  return window['go']['main']['App']['ModThumbnail'](arg1, arg2);
}

export function OpenModFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenModFolder'](arg1, arg2);
}

export function ReadModFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadModFile'](arg1, arg2, arg3);
}

export function SavePlayset(arg1) {
  return window['go']['main']['App']['SavePlayset'](arg1);
}

export function ScanGame(arg1, arg2) {
  return window['go']['main']['App']['ScanGame'](arg1, arg2);
}

export function SetPreferences(arg1) {
  return window['go']['main']['App']['SetPreferences'](arg1);
}

export function StartupNotice() {
  return window['go']['main']['App']['StartupNotice']();
}

export function WatchMods(arg1) {
  return window['go']['main']['App']['WatchMods'](arg1);
}
